<?php

namespace Tests;

use Mockery;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;
use PHPUnit\Framework\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    /**
     * @var vfsStreamDirectory
     */
    protected $vfs;

    protected function setUp(): void
    {
        $this->vfs = vfsStream::setup();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        Mockery::close();

        $this->vfs = null;
    }

    protected function resourcePath(string $path = ''): string
    {
        $defaultPath = __DIR__ . DIRECTORY_SEPARATOR . 'Fixture' . DIRECTORY_SEPARATOR . 'resources';

        return $defaultPath . ($path ? DIRECTORY_SEPARATOR . $path : $path);
    }
}
